<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Aktif' => '',
    'Are you sure you want to delete this item?' => '',
    'Create Perbelanjaan' => 'Tambah Perbelanjaan',
    'Create Perjalanan' => 'Tuntutan Perjalanan',
    'Create Perolehan' => 'Borang Perolehan',
    'Confirmation' => 'Pengesahan',
    'Butiran' => '',
    'Cari' => '',
    'Daftar' => '',
    'Daftar Pengguna' => '',
    'Date' => 'Tarikh',
    'Delete' => 'Padam',
    'Emel' => '',
    'ID' => '',
    'Id Jabatan' => '',
    'Id Unit' => '',
    'Jabatan' => '',
    'Kemaskini' => '',
    'Kemaskini Jabatan: {nameAttribute}' => '',
    'Kemaskini Pengguna: {nameAttribute}' => '',
    'Kemaskini Unit: {nameAttribute}' => '',
    'Level' => '',
    'Nama' => '',
    'Next' => 'Seterusnya',
    'No Kp' => '',
    'Padam' => '',
    'Padam item ini?' => '',
    'Password' => '',
    'Pengguna' => '',
    'Penggunas' => '',
    'Reset' => '',
    'Search' => '',
    'Select all' => 'Piih Semua',
    'Save' => 'Simpan',
    'Tambah Jabatan' => '',
    'Tambah Pengguna' => '',
    'Tambah Unit' => '',
    'The requested page does not exist.' => '',
    'Unit' => '',
    'Units' => 'Unit',
    'Unselect all' => 'Nyahpilih Semua',
    'Update' => 'Kemaskini'
];
